### ISSUE TITLE
unable to .add() or .delete()

### ISSUE THREAD

**Issue by sgarratt** [schneidsDotNet/Moq.EntityFramework#1]
Trying to write unit tests. Data can be initialized by using MockSetFor() without a problem. That data can later be found or updated. But I am unable to successfully call Add() on a mocked EF DBset. there is no error but DBset count is unchanged. Not sure if this is an error, or something I am doing wrong. Does Add() work ?

**Comment by schneidenbach** [comment]
Add() and Remove() are currently not supported.  Behaviorally, they are tricky to implement if I am to stay as close to Entity Framework as possible.

If you're testing when an object is added or removed from a context, you might be as well served by checking when an object is added or removed via Moq.  I'd need more information about your use case before I could help you further, but here's a quick example (modified from my README :)

```
public async Task PostTest()
{
    var controller = new PersonsController(contextMock.Object);
    var newPerson = new Person { Name = "John Lackey" };
    await controller.Post(newPerson);

    setMock.Verify(s => s.Add(newPerson), Times.Once());
    mockContext.Verify(c => c.SaveChangesAsync(), Times.Once());
}
```
